### ISSUE TITLE
Crossjoin\Browscap result

### ISSUE THREAD

**Issue by crossjoin** [kenjis/user-agent-parser-benchmarks#1]
Hi,

I just saw your benchmarks and would like to check the reason for the bad performance in your test, because I wonder a bit about it (differs a lot from my tests).
- Did you use the recommended settings (PHP >= 5.5)?
- Which Browscap file version did you use for your tests?
- Which other settings did you use (opcode cache etc.)?

Best,
Chris

**Comment by kenjis** [comment]
Thank you for your comment.

I wrote how to benchmark: https://github.com/kenjis/user-agent-parser-benchmarks#how-to-benchmark

Are your results differ a lot from my results?

The answer is below if my memory is correct:
- PHP 5.5
- Lite version
- use Opcache

**Comment by crossjoin** [comment]
I tried to run your benchmark (but it didn't work without modifications) and I think I found the reasons for the huge differences:
- Most parsers load all browscap data and cache it internally in the class, that's why they require a lot of memory. This costs a lot of resources first, but when checking multiple user agents at once, all using the cached data, this is the faster solution.
- With Crossjoin\Browscap I tried to reduce the memory consumption a lot, by loading only a minimum of the browscap data, without caching it in the class. And as you normally check only one user agent at a time, this is usually the more efficient variant.

So it's a question of what you want to test in your benchmark: multiple or only one user agent with each parser instance? IMHO checking one user agent is the usual use case...

Nevertheless you should differ both cases and clearly note that in your results:
- Test multiple user agents with one parser instance.
- Test multiple user agents with multiple parser instances (and with a reset of all data cached in the class itself).

I specially wondered about the relatively high memory consumption in your test. Usually it requires much less memory, only in special cases (depending on the user agent) Crossjoin\Browscap needs to do a bit more work. So the result is okay, but shouldn't you differ between the min/max/avg memory consumption in your benchmark?

Also I see that you compare parsers that use totally different data sets, and therefore cannot really be compared to each other. Perhaps you only need basic information, but of course you get much different results if you compare "ua-parser" or "woothee" (based on very small data sets) with a browscap based parser (providing much more information).

**Comment by kenjis** [comment]
> So it's a question of what you want to test in your benchmark: multiple or only one user agent with each parser instance? IMHO checking one user agent is the usual use case...

My goal is to find a better agent parser for my web apps/frameworks. And you're right my use case is to check a user agent of a vistitor in a request.

So what you say is my benchmark is not suit for my purpose, right?

Thank you for your comment. I will fix my benchmark.

**Comment by crossjoin** [comment]
Yes, if that's your goal, then your benchmark results are misleading. 

I also searched for a user agent parser for my projects and finally created Crossjoin\Browscap.

The main problem of other browscap parsers was the huge data set, resulting in memory errors especially in shared hosting environments, where you cannot adjust the settings. This was especially the case on the first request or when updating the browscap data.

So perhaps the initialization/preparation should also be checked in your benchmark?

**Comment by kenjis** [comment]
I fixed my bemchmark: https://github.com/kenjis/user-agent-parser-benchmarks/commit/244a5353075af32a1fe9abb3eb335c41b95f9b0e

And update the results: https://github.com/kenjis/user-agent-parser-benchmarks/commit/dba852818730eaa8cee470fae2379f41a99b3630

Thank you for your advice. `Crossjoin\Browscap` is the best replacement of  `get_browser()`.

**Comment by crossjoin** [comment]
Great, thanks for fixing it. And I'm happy about the result (although I also worked on improving the browscap-php project, and I won't stop testing new improvements :)).

I still would like to know the required resources for the initialization, I mean downloading and preparing new data, because this was the main problem with the memory in my test cases - but I know this is not applicable for all parsers and differs depending on the type of browscap data set used (small, medium, large), so perhaps it's not part of your benchmark.

**Comment by kenjis** [comment]
Thank you.

I'll check memory usage to download and prepare browsecap.ini. Yes, it is a problem to use extremely too much memory.

**Comment by kenjis** [comment]
I checked. `Crossjoin\Browscap` needs only 1/6 memory than browscap-php. It is amazing.

```
Updating browscap-php data...
 52.89607000351 secs 
 381,943,808 bytes
Updating crossjoin-browscap data...
 38.607126951218 secs 
 62,652,416 bytes
```
